#!/usr/bin/env bash

base() {
    # Need a directory tree
    $CRAPP --tmpkeep dirs --gitkeep --template base .
    # Need a PACKAGE file
    $CRAPP --tmpkeep pkg --template base .
    # Need a README file
    $CRAPP --tmpkeep readme --template base .
    # Need an .editorconfig
    $CRAPP --tmpkeep editorconfig --template base .
    # Need a .gitignore and .gitattributes
    $CRAPP --tmpkeep git --template base .
    # Need environments
    $CRAPP --tmpkeep dotenv --template base .
    # Need a Makefile
    $CRAPP --tmpkeep makefile --template base .
    # Need a .projectile
    touch .projectile
    # # Initialize git
    # git init
    # git add .
    # git config --local init.defaultBranch master
    # git commit -m 'Initial commit'
}
base
