#!/usr/bin/env bash

base() {
    debug scaffolding node base
    # need a directory tree
    ${DATADIR}/dirs/dirs.sh --template base
    # need to initialize npm
    pushd ${TEMPDIR}
    npm init -y
    popd
    # need a task runner
    ${DATADIR}/make/make.sh --template node-base Makefile
    # need a bundler
    # pushd ${TEMPDIR}
    # npm install --save-exact \
    #     esbuild
    # popd

    # need a linter
    pushd ${TEMPDIR}
    npx eslint --init
    popd

    # need a formatter
    pushd ${TEMPDIR}
    npm install --save-dev --save-exact prettier
    echo {}> .prettierrc.json
    popd

}
