#!/usr/bin/env bash

base() {

    [ $DRY_RUN ] && {
        cat ${BASH_SOURCE[0]}
        exit 0
    }

    pushd ${TEMPDIR} >/dev/null
    mkdir -p config/env 2>/dev/null
    touch config/env/env.default
    touch config/env/env.development
    touch config/env/env.testing
    touch config/env/env.production
    touch .env.default.local
    touch .env.development.local
    touch .env.testing.local
    touch .env.production.local
    popd >/dev/null
}
