#!/usr/bin/env bash

base() {
    debug scaffolding gitignore base

    [ $DRY_RUN ] && {
        ${DATADIR}/git/git.sh --template gitignore/transient --dry-run
        ${DATADIR}/git/git.sh --template gitignore/editors --dry-run
        exit 0
    }

    ${DATADIR}/git/git.sh --template gitignore/transient --dry-run >> \
              ${TEMPDIR}/${LOC_FILENAME:-$FILENAME}
    ${DATADIR}/git/git.sh --template gitignore/editors --dry-run >> \
              ${TEMPDIR}/${LOC_FILENAME:-$FILENAME}
}
