#!/usr/bin/env bash

base() {
    debug scaffolding dirs base
    pushd $TEMPDIR >/dev/null
    mkdir src
    mkdir tests
    mkdir tmp
    mkdir config
    mkdir config/env
    mkdir docs

    [ $GITKEEP ] && {
        touch src/.gitkeep
        touch tests/.gitkeep
        touch config/.gitkeep
        touch config/env/.gitkeep
        touch docs/.gitkeep
        touch tmp/.gitkeep
    }
    popd >/dev/null
}
