#!/usr/bin/env bash

web-app() {
    debug base dirs at $(realpath $TEMPDIR)
    pushd $TEMPDIR >/dev/null
    mkdir src
    mkdir src/hooks
    mkdir src/contexts
    mkdir src/components
    mkdir src/pages
    mkdir src/app
    mkdir src/utils
    mkdir src/services
    mkdir src/loaders
    mkdir src/routes
    mkdir tests
    mkdir tmp
    mkdir config
    mkdir config/env
    mkdir docs
    mkdir public
    mkdir scripts
    mkdir assets
    [ $GITKEEP ] && {
        touch src/.gitkeep
        touch src/hooks/.gitkeep
        touch src/contexts/.gitkeep
        touch src/components/.gitkeep
        touch src/pages/.gitkeep
        touch src/app/.gitkeep
        touch src/utils/.gitkeep
        touch src/services/.gitkeep
        touch src/loaders/.gitkeep
        touch src/routes/.gitkeep
        touch tests/.gitkeep
        touch tmp/.gitkeep
        touch config/.gitkeep
        touch config/env/.gitkeep
        touch docs/.gitkeep
        touch public/.gitkeep
        touch scripts/.gitkeep
        touch assets/.gitkeep
    }
    popd >/dev/null
}
