#!/usr/bin/env bash

react() {
    # base dirs
    $CRAPP --tmpkeep dirs --template base .

    if [ $DRY_RUN ]; then
        cat <<EOF
mkdir -p src/{hooks,components,services,pages,app,contexts,loaders,scratch}
mkdir -p assets/{backgrounds,brand,fonts,icons}
mkdir -p public/fonts
EOF
        exit 0
    fi

    # react dirs
    mkdir -p src/{hooks,components,services,pages,app,contexts,loaders,scratch}
    mkdir -p assets/{backgrounds,brand,fonts,icons}
    mkdir -p public/fonts

    [ $GITKEEP ] && {
        touch src/{hooks,components,services,pages,app,contexts,loaders,scratch}/.gitkeep
        touch assets/{backgrounds,brand,fonts,icons}/.gitkeep
        touch public/fonts/.gitkeep
    }
}

react
